use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let icons_dir = manifest_dir.join("icons");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=icons");
    println!("cargo:rerun-if-changed=icons/tray-icon.png");

    let generated = generate_frames(&icons_dir);
    fs::write(out_dir.join("frames.rs"), generated).expect("write frames.rs");

    tauri_build::build()
}

fn generate_frames(icons_dir: &Path) -> String {
    let mut out = String::from("// auto-generated by build.rs — do not edit\n\n");

    let mut anim_dirs: Vec<_> = fs::read_dir(icons_dir)
        .expect("read icons dir")
        .filter_map(|e| e.ok())
        .filter(|e| {
            let is_dir = e.file_type().map(|t| t.is_dir()).unwrap_or(false);
            let name = e.file_name().to_string_lossy().to_string();
            is_dir && (name == "anim" || name.starts_with("anim-"))
        })
        .collect();
    anim_dirs.sort_by_key(|e| e.file_name());

    for entry in anim_dirs {
        let dir_name = entry.file_name().to_string_lossy().to_string();
        let dir_path = entry.path();
        println!("cargo:rerun-if-changed={}", dir_path.display());

        let mut frames: Vec<String> = fs::read_dir(&dir_path)
            .expect("read anim dir")
            .filter_map(|e| e.ok())
            .filter_map(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                (name.starts_with("frame-") && name.ends_with(".png")).then_some(name)
            })
            .collect();
        frames.sort();

        if frames.is_empty() {
            panic!("no frame-*.png files in icons/{}", dir_name);
        }

        let ident = dir_name.replace('-', "_");
        let upper = ident.to_uppercase();
        out.push_str(&format!("pub const {}_LEN: usize = {};\n", upper, frames.len()));
        out.push_str(&format!(
            "pub fn {}(idx: usize) -> tauri::image::Image<'static> {{\n",
            ident
        ));
        out.push_str(&format!("    match idx % {}_LEN {{\n", upper));
        for (i, f) in frames.iter().enumerate() {
            let path = format!("icons/{}/{}", dir_name, f);
            if i + 1 == frames.len() {
                out.push_str(&format!(
                    "        _ => tauri::include_image!(\"{}\"),\n",
                    path
                ));
            } else {
                out.push_str(&format!(
                    "        {} => tauri::include_image!(\"{}\"),\n",
                    i, path
                ));
            }
        }
        out.push_str("    }\n}\n\n");
    }

    out
}
